// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLLFQEhWpPksDcYIRwcWPeGO_N1vQy1Es',
    appId: '1:351322982828:web:154b2b35755b427e835209',
    messagingSenderId: '351322982828',
    projectId: 'handong-software-engineering',
    authDomain: 'handong-software-engineering.firebaseapp.com',
    storageBucket: 'handong-software-engineering.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcz7GynYeipOxMnAdWDtOMnoHM5ndvr9c',
    appId: '1:351322982828:android:0cc514b30595d867835209',
    messagingSenderId: '351322982828',
    projectId: 'handong-software-engineering',
    storageBucket: 'handong-software-engineering.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBp1U6rqHr36WbowDDaAVh4ZrwQlPIYj9U',
    appId: '1:351322982828:ios:a99c8226dd8ce75d835209',
    messagingSenderId: '351322982828',
    projectId: 'handong-software-engineering',
    storageBucket: 'handong-software-engineering.appspot.com',
    iosClientId: '351322982828-f72e6edhimfpk7lec948j88ri2vcuouu.apps.googleusercontent.com',
    iosBundleId: 'com.example.softwareEngineering',
  );
}
